apiVersion: drowzee.challengr.io/v1beta1
kind: SleepSchedule
metadata:
  name: working-hours
spec:
  sleepTime: "10:00pm"
  wakeTime: "09:00am"
  dayOfWeek: "mon-fri"
  timezone: "Australia/Sydney"
  deployments:
    - name: dummy-service
  ingressName: dummy-service
---
apiVersion: drowzee.challengr.io/v1beta1
kind: SleepSchedule
metadata:
  name: every-day
spec:
  sleepTime: "10:00pm"
  wakeTime: "09:00am"
  dayOfWeek: "*"
  timezone: "Australia/Sydney"
  deployments:
    - name: service1
    - name: service1-worker
  cronjobs:
    - name: service1-backup
  ingressName: service1
---
apiVersion: drowzee.challengr.io/v1beta1
kind: SleepSchedule
metadata:
  name: permanent-down
spec:
  sleepTime: "08:00pm"
  dayOfWeek: "*"
  # No wakeTime defined - resources will remain scaled down indefinitely
  timezone: "Australia/Sydney"
  deployments:
    - name: non-prod-service
  statefulsets:
    - name: non-prod-database
  cronjobs:
    - name: non-prod-backup
  ingressName: non-prod-service
