apiVersion: drowzee.challengr.io/v1beta1
kind: SleepSchedule
metadata:
  name: testing
spec:
  sleepTime: '09:00pm'
  wakeTime: '09:00am'
  timezone: 'Australia/Sydney'
  deployments:
    - name: dummy-service
  ingressName: dummy-service
