{{- if .Values.role.enabled -}}
metadata:
  name: drowzee
  labels:
    k8s-app: drowzee
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
roleRef:
  name: drowzee
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: drowzee
    kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
{{- end }}