apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drowzee.fullname" . }}
  labels:
    {{- include "drowzee.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY_BASE: {{ .Values.secrets.secretKeyBase }}
