spec:
  scope: Namespaced
  group: drowzee.challengr.io
  names:
    kind: SleepSchedule
    plural: sleepschedules
    singular: sleepschedule
    shortNames:
      - ss
  versions:
    - name: v1beta1
      deprecated: false
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                hosts:
                  type: array
                  items:
                    type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      message:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                      type:
                        type: string
                      reason:
                        type: string
                      lastHeartbeatTime:
                        type: string
                        format: date-time
                      lastTransitionTime:
                        type: string
                        format: date-time
                observedGeneration:
                  type: integer
            spec:
              type: object
              required:
                - sleepTime
                - wakeTime
                - timezone
              properties:
                enabled:
                  type: boolean
                  description: Whether the schedule is enabled
                  default: true
                deployments:
                  type: array
                  description: The deployments that will be slept/woken.
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                statefulsets:
                  type: array
                  description: The statefulsets that will be slept/woken.
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                cronjobs:
                  type: array
                  description: The cronjobs that will be suspended/resumed.
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                needs:
                  type: array
                  description: List of other SleepSchedules that this schedule depends on. Dependencies will be woken up first during manual wake-up operations.
                  items:
                    type: object
                    required:
                      - name
                      - namespace
                    properties:
                      name:
                        type: string
                        description: Name of the dependency SleepSchedule
                      namespace:
                        type: string
                        description: Namespace of the dependency SleepSchedule
                ingressName:
                  type: string
                  description: The ingress that will be slept/woken.
                sleepTime:
                  type: string
                  description: "The time that the deployment will start sleeping (format: HH:MM for 24h or H:MMam/pm for 12h)"
                timezone:
                  type: string
                  description: The timezone that the input times are based in
                wakeTime:
                  type: string
                  description: "The time that the deployment will wake up (format: HH:MM for 24h or H:MMam/pm for 12h)"
                onDemand:
                  type: boolean
                  description: "If true, the schedule will not automatically wake up at wakeTime but will still auto-sleep at sleepTime. Manual overrides are still auto-removed at scheduled times. If false (default), schedule works normally with auto-wake and auto-sleep."
                  default: false
                dayOfWeek:
                  type: string
                  description: "Cron-like expression for days of the week when the schedule is active (0-6 or SUN-SAT). Examples: '1-5' for weekdays, '0,6' for weekends, '*' for all days (default)."
                  default: "*"
      storage: true
      additionalPrinterColumns:
        - name: Enabled
          type: string
          description: Enabled
          jsonPath: .spec.enabled
        - name: DayOfWeek
          type: string
          description: Active Days
          jsonPath: .spec.dayOfWeek
        - name: SleepTime
          type: string
          description: Starts Sleeping
          jsonPath: .spec.sleepTime
        - name: WakeTime
          type: string
          description: Wakes Up
          jsonPath: .spec.wakeTime
        - name: Timezone
          type: string
          description: Timezone
          jsonPath: .spec.timezone
        - name: Deployments
          type: string
          description: Deployments
          jsonPath: .spec.deployments[*].name
        - name: StatefulSets
          type: string
          description: StatefulSets
          jsonPath: .spec.statefulsets[*].name
        - name: CronJobs
          type: string
          description: CronJobs
          jsonPath: .spec.cronjobs[*].name
        - name: Needs
          type: string
          description: Dependencies
          jsonPath: .spec.needs[*].name
        - name: OnDemand
          type: string
          description: On Demand
          jsonPath: .spec.onDemand
        - name: Sleeping?
          type: string
          description: Current Status
          jsonPath: .status.conditions[?(@.type == "Sleeping")].status
        - name: Transitioning?
          type: string
          description: Status Change In Progress
          jsonPath: .status.conditions[?(@.type == "Transitioning")].status
        - name: ManualOverride?
          type: string
          description: Status overridden by user
          jsonPath: .status.conditions[?(@.type == "ManualOverride")].status
      served: true
metadata:
  name: sleepschedules.drowzee.challengr.io
  labels:
    k8s-app: drowzee
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
