name: Helm Chart Publisher

on:
  push:
    tags: [ "v*" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/')
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update Chart Versions
        run: |
          sed -i "s/^version: .*/version: ${{ steps.extract_version.outputs.version }}/" chart/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: \"${{ steps.extract_version.outputs.version }}\"/" chart/Chart.yaml

      - name: Retrieve existing charts
        run: |
          git clone --branch gh-pages https://github.com/col/drowzee.git existing-charts
          mkdir -p packaged-charts
          cp -n existing-charts/*.tgz packaged-charts/ || true

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Chart
        run: helm package ./chart --destination ./packaged-charts

      - name: Generate Repository Index
        run: |
          helm repo index ./packaged-charts --url https://col.github.io/drowzee

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packaged-charts
          keep_files: true
          force_orphan: true
          destination_dir: .
